version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env   
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: .
    command: celery -A Carts worker -l INFO
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - web
  
  celery-beat:
    restart: always
    build: .
    volumes:
       - .:/code
    command: bash -c "python manage.py migrate && celery -A Carts beat -l INFO  --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
       - redis
