# Generated by Django 4.0.4 on 2022-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('1', 'not active'), ('2', 'activated'), ('3', 'expired')], default=2, max_length=50),
        ),
    ]
