# Generated by Django 3.2.13 on 2022-04-25 10:51

import CartApp.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_cart_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expires_at',
            field=enumchoicefield.fields.EnumChoiceField(default=CartApp.models.ExpiresChoices['year'], enum_class=CartApp.models.ExpiresChoices, max_length=9),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=CartApp.models.StatusChoices['active'], enum_class=CartApp.models.StatusChoices, max_length=10),
        ),
    ]
